name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./CM.WeeklyTeamReport
      run: dotnet restore
    - name: Build
      working-directory: ./CM.WeeklyTeamReport
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./CM.WeeklyTeamReport
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Codecov upload
      uses: codecov/codecov-action@v2
